### ISSUE TITLE
Bug in 7.7.2

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#12]
7.7.2	Edit List Box ('elst')
For video CMAF Tracks, the EditBox and in particular the EditListBox shall not be present.
For **video** CMAF Track files as well as any other media types, the EditListBox may be present following the constraints in subclause 7.5.13.

this **video** should be replaced with audio.

**Comment by mikedo** [comment]
Yes. While we're at it, this sentence in 9.2.5 implies that it can be used in video.  Perhaps just delete it?

> A video track shall not use both signed composition offsets and an EditListBox.

Or not, since it is permitted in other structural brands.  Confusing, but not wrong.

**Comment by sdp198** [comment]
I believe the word video there is correct.  Audio would come under the "any other media type" category.

There was a lot of discussion about this in 2016.  The early drafts of CMAF required the use of a v1 trun box and negative composition time offsets.  However there was a request that it be relaxed to allow existing DASH ondemand profile content to be used with older clients that did not support v1 trun boxes.  The eventual compromise (or perhaps bodge) was to allow v0 trun with edit list only for CMAF Track Files.

The text in a draft in May 2016 said:
`CMAF video tracks shall either
a) contain version 1 TrackRunBoxes in CMAF video fragments with composition offsets
(negative composition offsets where necessary) to adjust the earliest media sample
presentation time in each CMAF fragment to equal the earliest media sample decode time,
which is equal to the baseMediaDecodeTime field of the
TrackFragmentBaseMediaDecodeTimeBox, or
b) contain an offset edit list in the associated CMAF header to subtract the composition delay
added by positive composition offsets, if and only if the CMAF track is contained in a CMAF
track file containing version 0 TrackRunBoxes.`

I think what is wrong with 7.7.2 is that the first sentence really needs to end with "unless it is [also/stored as] a CMAF Track File" or something with similar meaning.

**Comment by cconcolato** [comment]
I think we could use a more general cleaning (again!) on the use of edit list. Unfortunately, I missed the deadline to prepare a contribution but I had done this Google doc which might be useful: https://docs.google.com/document/d/1KplnJ-u2GvfG6pMZyb1VzZF2ZNmBX_evcsbWxV-iDcE/edit?usp=sharing

**Comment by cconcolato** [comment]
The recommendation of the group is to study the above document, agree on the intent (currently only prohibiting edit lists in video in cmf2) and then we can draft text to fix the spec to match the intent.

**Comment by haudiobe** [comment]
I fixed the obvious bug on audio in the draft third edition.

**Comment by cconcolato** [comment]
@haudiobe Changing *video* to *audio* does not completely match the table in the document I shared in my previous comment. Let's first agree on what we want to clarify globally rather than make multiple small changes.

**Comment by haudiobe** [comment]
addressed here: https://dms.mpeg.expert/doc_end_user/documents/137_OnLine/wg11/m58936-v2-m58936-Issues-r1.zip

Proposal: 
1)	do not change video to audio in the third edition.
2)	Explicitly add CMAF Tracks to show the difference
3)	Make Track files explicit.
4)	Continue to study the doc: https://docs.google.com/document/d/1KplnJ-u2GvfG6pMZyb1VzZF2ZNmBX_evcsbWxV-iDcE/edit

**Comment by krasimirkolarov** [comment]
MPEG 140: Keep it for 1 more cycle

**Comment by haudiobe** [comment]
1, 2, 3 are implemented in third edition.

on 4, I asked JCCP developers to have a look.

Proposal is to close issue and open a new one with 4 only.

**Comment by krasimirkolarov** [comment]
Leave it open for one more cycle (Cyril to follow up).

**Comment by podborski** [comment]
@cconcolato did you follow up? :)

**Comment by krasimirkolarov** [comment]
From BoG at MPEG146: Thomas and Cyril will work on bringing this at the next meeting.

**Comment by krasimirkolarov** [comment]
Contribution was submitted at MPEG147 and is integrated in the Working Draft of Amd 2 of Ed 3 of CMAF
