### ISSUE TITLE
nmhd is missing in Table 3

### ISSUE THREAD

**Issue by RufaelDev** [MPEGGroup/CMAF#13]
Table 3 of CMAF specification misses the null media header (nmhd), 
but this is used for CMAF metadata and wvtt tracks!  

please confirm/comment about this as to avoid confusion about the usage of this box in CMAF.

Thank you!

**Comment by sdp198** [comment]
I thought web VTT was removed from CMAF in the early drafts stage?

For metadata, it might be easier to add this at the point that a CMAF Metadata profile is added?

**Comment by cconcolato** [comment]
@sdp198 Section 11 of CMAF covers Subtitles, and it includes WebVTT and TTML. Section A.4 defines Subtitle CMAF media profiles and brands.

**Comment by sdp198** [comment]
> 
> 
> @sdp198 Section 11 of CMAF covers Subtitles, and it includes WebVTT and TTML. Section A.4 defines Subtitle CMAF media profiles and brands.

So it does.  My mistake.

**Comment by cconcolato** [comment]
I think there is agreement on this issue and we should fix the spec when we can.

**Comment by RufaelDev** [comment]
agree with @cconcolato, while on it we also noticed the pssh box was missing in table 5 was this intentional ? Specification text is very clear that pssh box may be included , not having it in the table may cause confusion down the line.

**Comment by cconcolato** [comment]
The group discussed the issue and decided to add text  to the amendment and to close this issue.
