### ISSUE TITLE
Table 11: elst

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#14]
Change:

elst | Shall   be identical except for video CMAF track files with a different composition   offset
-- | --

to

elst | Shall be identical except for video CMAF track with a different composition offset
-- | --

In the second edition, edit lists may also occur in CMAF track files.

**Comment by cconcolato** [comment]
This should be discussed as part of #12  and edit lists in general

**Comment by haudiobe** [comment]
Proposal:
1)	Propose to fix this obvious bug => addressed here https://dms.mpeg.expert/doc_end_user/documents/137_OnLine/wg11/m58936-v2-m58936-Issues-r1.zip
2)	Continue to study the doc in #12
3)	Close this issue
