### ISSUE TITLE
Missing and Sparse CMAF Fragments and Segments (TuC)

### ISSUE THREAD

**Issue by RufaelDev** [MPEGGroup/CMAF#15]
While a CMAF presentation is continuous and does not have gaps, some segments or fragments may be missing content (alternative video frames or silence is inserted) or content is sparse  (e.g) no subtitle. 

the proposal is if it is possible to mark such segment as to allow client or other 
processing to happen on it later to possibly correct it. 

One way to do so would be to introduce brands for sparse segment and missing segment. This way a client or processor knows that the segment is containing sparse or missing content. The proposal is not to allow or introduce gaps, but intead allow marking of missing/sparse content that is "filled" with filler content

**Comment by ZmGorynych** [comment]
We need to allow "empty" segments as otherwise the transcoder would be required to always output pictures, which is both a waste of bandwidth and an additional operational issue (different channels may want different slates, etc). 
A player receiving a "missing" segment will use its own logic (e.g. display a canned PNG or sequence) as opposed to displaying whatever the encoder is supposed to generate.

**Comment by ZmGorynych** [comment]
Please consider compatibility with the existing DASH "Missing Content Segment" construct as specified in sec. 6.2.6 of the 4th edition of MPEG DASH. 

> 6.2.6	Missing Content Segment
> A Missing Content Segment is defined for the purpose to extend the Segment Timeline even if the data in the Segment is not present or is only partially present. This Segment contains no or a subset of media samples of the media timeline duration it is representing. If the Segment is not a decodable media segment, then the segment shall include a major brand 'miss'. The Segment may additionally contain an 'emsg', for example, to indicate an MPD validity expiration event.
> In addition, for a Missing Content Segment, the following shall hold:
> -	a single Segment Index ('sidx') box shall be present and the values of the Segment Index shall describe accurate timing of the Segment Timeline, i.e., 
> o	the earliest_presentation_time in the 'sidx'box shall be the value of S@t as signaled in the Segment Timeline in the MPD
> o	the Subsegment_duration fields in the 'sidx' box shall be the value of S@d as signaled in the Segment Timeline in the in the MPD
> Note: By forcing these values, the DASH Client is able to properly extend the Segment Timeline even though no actual media data may be present.
>

**Comment by RufaelDev** [comment]
@ZmGorynych that can also be considered, I removed mentioning encoder/packager as this might not be the right place to discuss about that.

**Comment by cconcolato** [comment]
For sparse content (subtitles), the new edition of CMAF will integrate text. For missing segments, we added text also indicating that a true gap is non conforming but parts in between are conforming.
