### ISSUE TITLE
minimum fragment duration of 960 ms

### ISSUE THREAD

**Issue by RufaelDev** [MPEGGroup/CMAF#19]
For low latency streaming, one of the options is using short CMAF fragments. Right now 1 second is defined as the minimum fragment duration in 7.3.2.4. 960 ms might be more suitable as for common framerates/sample rates you can achieve alignment of fragment boundaries for audio and video (e.g. 45 when 1024 per iso sample or 30 for 1536 per iso sample).  DVB chose this value for its low latency specification using short independent segments and would like to align with cmaf framgnts if possible.

**Comment by cconcolato** [comment]
This refers to bullet point f) in 7.3.2.4. IIUC it is suggesting to replace "one second" with "960 ms".

**Comment by cconcolato** [comment]
FYI, I just checked the intermediate draft of the 3rd edition, and it still mentions "one second"

**Comment by RufaelDev** [comment]
Any chance to still correct this still or will this be kept as is ?

**Comment by cconcolato** [comment]
As discussed today, we have an agreement to make this change.

**Comment by haudiobe** [comment]
Addressed here: https://dms.mpeg.expert/doc_end_user/documents/137_OnLine/wg11/m58936-v2-m58936-Issues-r1.zip
