### ISSUE TITLE
CTA WAVE: Inband tracks: NGA audio preselections

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#20]
https://github.com/cta-wave/CMAF-Byte-Stream/issues/31

**Comment by cconcolato** [comment]
@haudiobe can you elaborate on this issue? What are you requesting the group does?

**Comment by haudiobe** [comment]
Proposal:
1)	Mostly related CMAF inband tracks spec
2)	It is an interesting problem, but requires quite detailed discussion
3)	The CMAF byte stream format (that was never progressed) defines CMAF inband track handling – is this something to be added to the CMAF specification?
4)	Be aware of the issue
5)	Add a detailed description to the multi-track document referring to https://github.com/cta-wave/CMAF-Byte-Stream/issues/31
6)	Close the issue

**Comment by haudiobe** [comment]
It would be good to get feedback on W3C work on audio preselection.

**Comment by krasimirkolarov** [comment]
Overtaken by events. Close the issue
