### ISSUE TITLE
CTA WAVE: Preference to use textual user data item

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#21]
https://github.com/cta-wave/CMAF-Byte-Stream/issues/22

**Comment by cconcolato** [comment]
@haudiobe can you elaborate on this issue? What do you want the CMAF group to do?

**Comment by cconcolato** [comment]
@krasimirkolarov to study if anything needs to be done in CMAF

**Comment by haudiobe** [comment]
Proposal:
1)	It is a new feature that would be worthwhile to be discussed on how to add “human-readable labels to CMAF Tracks.
2)	Add the issue discussed here https://github.com/cta-wave/CMAF-Byte-Stream/issues/22#issuecomment-701693094  to TUC under “human-readable label”
3)	Close the issue.

**Comment by haudiobe** [comment]
Proposal remains to add to TUC

**Comment by krasimirkolarov** [comment]
We will add to the ongoing TuC
