### ISSUE TITLE
CTA WAVE: Use of a compatibility brand in a file type box or track type box

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#22]
https://github.com/cta-wave/CMAF-Byte-Stream/issues/21

**Comment by cconcolato** [comment]
Looking that the CTA-WAVE issue, the request seems to be :
>  we recommend the definition and use of a child box in the video sample description in order to signal the presence [of 608/708 captions] embedded in video. 

This seems to be an ISOBMFF issue first. @krasimirkolarov @dwsinger ?

**Comment by dwsinger** [comment]
we should look at the SEIs-on-SEIs as I think we can assert in them that the appropriate SEIs for CEAx08 are present, and the SEI-on-SEI could be in the config array

**Comment by haudiobe** [comment]
Proposal:
1)	It is a new feature that would be worthwhile to be discussed on how to add “video sample description in order to signal the presence [of 608/708 captions] embedded in video.”, However, this is only a specific case as rightfully indicated.
2)	There is a proposal to SEI-on-SEI: https://github.com/MPEGGroup/CMAF/issues/22#issuecomment-985786067 into the sample entry to indicated the presence and details on contained SEIs.
3)	This is a good feature and we propose to add this to the TUC under “SEI presence signaling in the sample entry”
4)	Close the issue.

**Comment by mikedo** [comment]
The presence of 608/708 (in video) is what the 'ccea' compatible brand does. Additionally useful would be to signal the caption tracks, languages, etc and that's what the strings defined in SCTE 128-1 do. See also DASH-IF ATSC IOP v1.1 (although there are syntax bugs so rely on the work in process SCTE 128-1). We should find place to store the latter strings where they could be extracted to populate (e.g. DASH) manifests.

**Comment by krasimirkolarov** [comment]
MPEG140: Keep this issue for one more cycle, unless there is further feedback

**Comment by haudiobe** [comment]
The proposal remains to add this to the TUC.

**Comment by RufaelDev** [comment]
@mikedo is it possible to map this information in these string from SEI messages in the sample entry ? Storing such SEI message in the Sample Entry to describe the SEI messages in the rest of the streams makes a lot of sense to me.

**Comment by krasimirkolarov** [comment]
We will add that issue to the current CMAF TuC as captured in the BoG notes

**Comment by krasimirkolarov** [comment]
we want to expose the presence of certain SEIs through ISOBMFF tools which include:
-	Brand
-	Sample entry information (SEI in SEI)
-	T35 Sample groups
