### ISSUE TITLE
CTA WAVE: A.6: Kind box for audio/video

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#23]
https://github.com/cta-wave/CMAF-Byte-Stream/issues/18

**Comment by cconcolato** [comment]
The request seems to be to clarify CMAF that multiple `kind` boxes may be present in a CMAF track, for example to provide the same semantics in multiple schemes. Is that correct @haudiobe ?

**Comment by haudiobe** [comment]
Proposal:
1)	The comment: https://github.com/MPEGGroup/CMAF/issues/23#issuecomment-983147722 is correct to add a clarification that multiple kind boxes may be present in a CMAF track, for example to provide the same semantics in multiple schemes.
2)	A text proposal is provided as follows in clause 7.5.3: 
Multiple KindBoxes may be present in a single CMAF Track.
3)	Close issue

Also addressed here: https://dms.mpeg.expert/doc_end_user/documents/137_OnLine/wg11/m58936-v2-m58936-Issues-r1.zip

**Comment by haudiobe** [comment]
BOG AF MPEG#139

please provide proposal for adding it to an ongoing Amd.

**Comment by krasimirkolarov** [comment]
MPEG 140: Keep this for one more cycle

**Comment by haudiobe** [comment]
Proposal: add this to the next amendment

**Comment by krasimirkolarov** [comment]
Add to the TuC
