### ISSUE TITLE
negative earliest presentation time in sidx in corner cases

### ISSUE THREAD

**Issue by RufaelDev** [MPEGGroup/CMAF#27]
As edit lists may be used to remove samples from the presentation timeline, in case a short segment exist in VoD with only 1 sample or a few samples that are all not intended for display, that segment may have an earliest presentation time before the presentation as it is edited out. What value should we put in the sidx box as it can only carry positive earliest presentation time as it is an unsigned integer. Does it make sense to document this case for the usage of sidx in CMAF ?

**Comment by cconcolato** [comment]
> that segment may have an earliest presentation time before the presentation as it is edited out

Does it have a presentation at all? If it's edited out, I would say it does not have a presentation time and does not qualify to be used for setting the earliest presentation time. 

This issue seems to be already discussed in #28. Can you clarify the differences or close one of the two?

**Comment by RufaelDev** [comment]
We can discuss them combined, originally #27 was on the negative sidx ept and #28 on the question if CMAF fragments with no samples to present are still valid.

**Comment by cconcolato** [comment]
Let's keep one for CMAF, and discuss whether we permit segments with non-presentable samples, and move the other one to ISOBMFF.

**Comment by RufaelDev** [comment]
OK maybe close this one then, and bring it to ISOBMFF discussion
