### ISSUE TITLE
CMAF Track Duration Requirement

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#3]
This is the third issue from: http://mpegx.int-evry.fr/software/ApplicationFormat/CMAF/issues/2
3)	The requirement of CMAF Track duration is unclear

From 7.3.6 in ISO/IEC 23000-19: CMAF tracks in a CMAF presentation shall equal the CMAF presentation duration, within a tolerance of the longest video CMAF fragment duration.

The whole issue is a bit artificial, but the problem is that this is not really useful. And secondly very hard to check on conformance. One issue we typically try to avoid are gaps. So one good sentence would be that CMAF tracks in a CMAF presentation shall be at least as long as the CMAF presentation duration, if this is acceptable. This would make every track spanning the whole presentation with media.

**Comment by cconcolato** [comment]
I don't find the definition unclear. It means that each track shall have a duration within the interval [longest track duration - longest video fragment duration, longest track duration].

I agree that it makes conformance harder. 

When you say you want to avoid gaps, what do you mean in this context? You will not be able to have exact durations for all tracks.
