### ISSUE TITLE
Signaling of Signal Properties for CMAF Content

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#30]
In the context of the new media profiles and the LS from SCTE, it was discussed on how to signal characteristics of the signal if not using the media profiles. It was proposed to use for example the CICP signaling for transfer characteristics. It may be beneficial to add an informative Annex to the CMAF specification that explains how MPEG specifications (or other available specs such as W3C media capabilities APIs) can support the signaling of specific parameters in advance, for example in a manifest. Some work on this was done for example in CTA WAVE on Media Capability support in [Draft Media Capabilities](https://github.com/MPEGGroup/CMAF/files/6828802/Media.Capabilities.-.TWG.docx) as well as in DASH Profile for CMAF content. Please provide feedback
1) general support/concern of adding such a specific Annex
2) specific parameters for which a signaling should be added

Input is encouraged for MPEG#136

**Comment by haudiobe** [comment]
We propose to address the issue by creating a new Annex on this topic on Guidelines and Recommendations for signaling CMAF Track and Switching Set properties in a manifest.

**Comment by krasimirkolarov** [comment]
No further comments received.
