### ISSUE TITLE
general_non_packed_constraint_flag to ?

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#32]
It says

H.4.2.6.1	SPS fields
Sequence parameter set NAL units that occur within a CMAF scalable HEVC track shall conform to ISO/IEC 23008-2:2017, Annexes F and H with the following additional constraints:
—	The following fields shall have pre-determined values as follows:
—	general_progressive_source_flag shall be set to 1.
—	general_frame_only_constraint_flag shall be set to 1.
—	general_interlaced_source_flag shall be set to 0.
*—	general_non_packed_constraint_flag shall be set to 0.*

This is very uncommon, it is usually set to 1. Bug?

**Comment by cconcolato** [comment]
For context, from the HEVC spec:
> `general_non_packed_constraint_flag` equal to 1 specifies that there are no frame packing arrangement SEI messages, segmented rectangular frame packing arrangement SEI messages, equirectangular projection SEI messages, or cubemap projection SEI messages present in the CVS. `general_non_packed_constraint_flag` equal to 0 indicates that there may or may not be one or more frame packing arrangement SEI messages, segmented rectangular frame packing arrangement SEI messages, equirectangular projection SEI messages, or cubemap projection SEI messages present in the CVS.

> NOTE 2 – Decoders may ignore the value of `general_non_packed_constraint_flag`, as there are no decoding process requirements associated with the presence or interpretation of frame packing arrangement SEI messages, segmented rectangular frame packing arrangement SEI messages, equirectangular projection SEI messages, or cubemap projection SEI messages.

Given the above text, I can imagine that 0 was chosen to: reduce syntax options (no need to check conformance for 0 and 1), while retaining all options (presence or absence of the SEI messages). I'm not sure it's worth changing it.

**Comment by haudiobe** [comment]
This is fixed in the draft third edition and can be closed.

**Comment by cconcolato** [comment]
What did you fix?

**Comment by haudiobe** [comment]
The issue is addressed in the draft third edition.

We propose to close the issue.
