### ISSUE TITLE
chroma_idc

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#33]
None of the media profiles set the chroma_idc to a specific value, but chroma_idc should be set to 1 for 4:2:0. Propose to fix this.

**Comment by sdp198** [comment]
For HEVC it's already restricted to this by the requirement to use Main or Main 10 profiles.
For AVC it's restricted to 0 or 1 (where 0 would be monochrome) by the limit of using High Profile which only allows  those values.  Other common profiles (Constrained Baseline, Main) don't allow it to be present (resulting in 1 as a default).  Do you want to explicitly prevent monochrome video?

**Comment by haudiobe** [comment]
We propose to set chroma_idc to 1 for HEVC profiles. This is not yet addressed in any document as it requires some efforts.

**Comment by sdp198** [comment]
I don't think that is necessary.  The HEVC profiles currently in the spec only allow either Main profile or Main 10.
In the HEVC specification for Main profile:
Active SPSs for the base layer shall have chroma_format_idc equal to 1 only.

In the HEVC specification for Main 10 profile:
– Active SPSs for the base layer shall have chroma_format_idc equal to 1 only.

It would be a duplication to add that separately into CMAF.  Elsewhere in the spec notes or non normative language have been used when a restriction comes from elsewhere, if you feel it's really necessary to highlight in CMAF.
