### ISSUE TITLE
aspect_ratio_idc not always set to 1

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#34]
Are there cases in CMAF for which we want the aspect_ratio_idc not be set to 1, i.e. non-square pixels?

**Comment by sdp198** [comment]
At the time the first edition of CMAF was being written square pixels seemed to be the direction of travel for media streaming.

**Comment by haudiobe** [comment]
We propose to set aspect_ratio_idc to 1 for HEVC and all new video profiles. This is not yet addressed in the document.

**Comment by haudiobe** [comment]
BOG AF MPEG#139

addressed in 3rd edition

close the issue
