### ISSUE TITLE
[ATSC] VVC CMAF bit depth (sps_bitdepth_minus8)

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/CMAF#37]
We note that in Table M.1, SDR supports both 8 and 10-bit depths.  ATSC does not intend to support 8-bit (only 10-bit).  Therefore only permitted value of sps_bitdepth_minus8 is 2, even for SDR. The rationale is:
o	Production side has long migrated to 10 bits.
o	Even film based content is not digitized at 8 bits.
o	Benefit of staying at 10 bits for the decoder.
o	No need to do additional tricks when content bit depth changes at both the encoder and decoder
o	A 10 bit decoder can handle 8 bits but there is a necessity to test and verify all the permutations. Staying with 10 bits drops the number of use cases in half.
ATSC constraint is more restrictive than the proposed CMAF constraint. This does not present a problematic incompatibility for ATSC.  ATSC suggests considering a similar constraint.

**Comment by krasimirkolarov** [comment]
Thanks you for the comment. DVB allows both 8 bit and 10 bit and we want to keep both in the profile for compatibility.
