### ISSUE TITLE
[ATSC] VVC CMAF HLG transfer characteristics (transfer_characteristics)

### ISSUE THREAD

**Issue by mikedo** [MPEGGroup/CMAF#38]
We note that in Table M.1, HLG transfer characteristics can be set to either 14 or 18. ATSC does not intend to support 14. In this instance, the ATSC constraint is more restrictive than the proposed CMAF constraint. This does not present a problematic incompatibility for ATSC, it is provided for information only.

**Comment by krasimirkolarov** [comment]
Thanks you for the comment. DVB uses both codes and it could create conflict if we only allow one. We will leave it as is.
