### ISSUE TITLE
9.2.5 excludes the case of SAP type 1 and trun v0

### ISSUE THREAD

**Issue by RufaelDev** [MPEGGroup/CMAF#42]
From ISO/IEC 23000-19 (3rd edition): 

9.2.5	Video CMAF fragment presentation time
CMAF video tracks shall either

a)	contain version 1 TrackRunBoxes in CMAF video fragments with composition offsets (negative composition offsets where necessary) to adjust the earliest media sample presentation time in each CMAF fragment to equal the earliest media sample decode time, which is equal to the baseMediaDecodeTime field of the TrackFragmentBaseMediaDecodeTimeBox, or

b)	contain an offset edit list in the associated CMAF header to subtract the composition delay added by positive composition offsets, if and only if the CMAF track is contained in a CMAF track file containing version 0 TrackRunBoxes.
A video track shall not use both signed composition offsets and an EditListBox.

This excludes the case when decode and presentation time of first sample are equal, in that case there is no need to adjust the earliest media presentation time, and you can still use trun box version 0 without using an EditListBox. I suggest adding this as a third option, or make 9.2.5 conditional only to the case when the decode and presentation time of the first sample are not equal and the first sample is also not the first sample in presentation order.

**Comment by krasimirkolarov** [comment]
Addressed in contribution m62174
