### ISSUE TITLE
Relaxing single track requirement for metadata tracks

### ISSUE THREAD

**Issue by podborski** [MPEGGroup/CMAF#46]
In general, CMAF is designed to disallow multiple tracks (`'trak'` boxes) in a single CMAF track. This need of simplicity is well justified for audiovisual media data. However, there are use cases for low bitrate metadata that is instructive for video presentations, such metadata can be best delivered as a track together with the respective media (in this case video) data.

We believe that we should explore how such use cases can be enabled. E.g. allowing the presence of the metadata track in addition to a video track in a single CMAF track. We are particularly interested in the multiplexed metadata `mebx` track.

**Comment by krasimirkolarov** [comment]
From the discussion at MPEG146:
Need more description of the use case. It could be a complex issue for CMAF to consider, given the current structure.
Another consideration is whether software will need to be changed from single track to multiple tracks support in CMAF.
Is there a way to have the data attached to the track, but keeping it to a single track compatible to CMAF. Sample group, sample auxiliary information?
Maybe explore on file format level if we can multiply levels?
The belief is that it is a relevant use case, need to explore better ways to solve it.
Use cases, complexities?
Also, perhaps bring up contribution on the topic at next meeting.

**Comment by krasimirkolarov** [comment]
Contribution was submitted at MPEG147 and is integrated in the Working Draft of Amd 2 of Ed 3 of CMAF
