### ISSUE TITLE
Sequence of Presentations

### ISSUE THREAD

**Issue by haudiobe** [MPEGGroup/CMAF#5]
This refers to the first part of the fifth proposal of http://mpegx.int-evry.fr/software/ApplicationFormat/CMAF/issues/2

In ISO/IEC 23000-19, it is said:

_From 6.6.8: Decode time discontinuities between CMAF fragments can result from starting a new CMAF presentation in a playlist, for example, in sequenced programs or programs interspersed with prerecorded ads. A manifest can locate the new CMAF presentation on its manifest presentation timeline and adjust CMAF switching set presentation time offsets accordingly._

In draft DASH-IF v5 we say now

_The mapping to DASH can be accomplished in different means. However, in any such cases, the sequencing of CMAF Presentations is done through a sequence of Periods. Specifically, it is assumed that the CMAF Presentations are played in sequence as follows: For any CMAF Presentation i=1, …, N, PST[i] reflects the actual time that elapses after playing the media of all prior CMAF Presentation for the durations of the CMAF Presentation in the sequence of these presentations relative to the PST[1] of the first CMAF Presentation in the sequence. The Period extends until the PST of the next CMAF Presentation, or until the end of the sequenced presentation in the case of the last CMAF Presentation. The difference between the PST[i] of a CMAF Presentation and the PST[i+1] time of the following CMAF Presentation, is the presentation duration PD[i] in Media Presentation time of the media content represented.
The mapping results now in a 1-1 mapping of the CMAF Presentations to Periods, and in addition, results in the mapping of a sequence of CMAF Presentations as defined above to a DASH Media Presentation, composed by a sequence of Periods._

Period boundaries permit continuity of the timeline or discontinuity. Continuity can be considered in different domains. 
1. Continuity in terms that the presentation time is continuous across Period boundaries. DASH permits both, timeline continuity or discontinuity.
2. Continuity in terms of remaining in the Initialization of a single CMAF Switching Set/DASH Adaptation Set, or to terminate and re-initialize.

Nothing must to be done here in CMAF, but generally  additional requirements for playback of a sequence of period and the requirements may be added to CMAF. DASH-IF currently doing all of these details, and it the question whether some this is preferably moved to CMAF.

**Comment by cconcolato** [comment]
> Nothing must to be done here in CMAF, but generally additional requirements for playback of a sequence of period and the requirements may be added to CMAF.

It seems that no action needs to be taken on the CMAF side. If so, can we close this issue? If not, do you have an example of what would need to be specified in CMAF?

**Comment by haudiobe** [comment]
I want to understand from people in CMAF if there is no intention to work on CMAF Presentation sequencing. If this ok, then we will "have to" do it outside CMAF. And DASH/DASH-IF a good place.

**Comment by roger-on-github** [comment]
Might be worth adding something to ISO/IEC 23000-19 Appendix D, "Hypothetical player model"

**Comment by cconcolato** [comment]
The CMAF group discussed this issue and agreed to incorporate text based on the above into Annex D.
